### PR TITLE
Fix broken image link in Assembly Instruction markdown files

### PR DESCRIPTION
**Pull request by brock**
* rename power_cable.JPG to power_cable.jpg to fix broken image in the Assembly Instruction markdown files

This was appearing as a broken image in both markdown files (english and german) https://github.com/oe1wkl/Morserino-32/blob/master/Documentation/Assembly%20Instructions/Detailed%20Assembly%20Instructions.md#step-by-step-instructions-at-least-read-them-even-if-you-decide-to-do-it-differently

### CODE REVIEW

**Comment by oe1wkl** [comment]
Not sure which branch or version you have got ... in my GitHub the file IS called power_cable.jpg ?

**Comment by brock** [comment]
Sorry for the delay, I replied to the email but it appears I'm not setup for that.

If you look at the list of filenames in the [Images](https://github.com/oe1wkl/Morserino-32/tree/master/Documentation/Assembly%20Instructions/Images) folder on Github, this file had the extension capitalized.

**Comment by oe1wkl** [comment]
Ok, I misunderstood apparently. This has been done.

**Comment by brock** [comment]
Take a look at the naming here:
https://github.com/oe1wkl/Morserino-32/tree/master/Documentation/Assembly%20Instructions/Images

For me it shows as uppercase, and the readme online shows a broken image

**Comment by oe1wkl** [comment]
Check agn, pls. It should be fixed now. WVon meinem Mobiltelefon gesendetAm 11.10.2022 um 09:27 schrieb Brock Angelo ***@***.***>:﻿
Take a look at the naming here:
https://github.com/oe1wkl/Morserino-32/tree/master/Documentation/Assembly%20Instructions/Images

For me it shows as uppercase, and the readme online shows a broken image

**Pull request merged**
